### ISSUE TITLE
Is hi3536dv100 and hi3536ev100 the same?

### ISSUE THREAD

**Issue by zhuwei** [OpenIPC/sandbox-fpv#1]

**Comment by whoim2** [comment]
https://github.com/OpenIPC/firmware/tree/master/br-ext-chip-goke/configs

Only v200 and v300, and others brands - join to out chat. Im recommend ivg-g2s for first start.

**Comment by zhuwei** [comment]
Okay, is it the same for using hi3536dv100 and hi3536ev100 on the ground?

**Comment by whoim2** [comment]
Theoretically yes, but im try only dv100

> Okay, is it the same for using hi3536dv100 and hi3536ev100 on the ground?
