### ISSUE TITLE
About of driver  libsns_imx307_2l_720p_50fps.so

### ISSUE THREAD

**Issue by Lance0724** [OpenIPC/sandbox-fpv#7]
Where to find this driver for Hi3516EV200 （ libsns_imx307_2l_720p_50fps.so）?

**Comment by Yury-MonZon** [comment]
[Here](https://github.com/OpenIPC/sandbox-fpv/raw/0e57f8564e89bd9986c41468945e4a204483bcd4/gk7205v200/usr/lib/sensors/libsns_imx307_2l_720p_50fps.so)

**Comment by Lance0724** [comment]
> [Here](https://github.com/OpenIPC/sandbox-fpv/raw/0e57f8564e89bd9986c41468945e4a204483bcd4/gk7205v200/usr/lib/sensors/libsns_imx307_2l_720p_50fps.so)

This so is compiled using gkSDK, right?  
Hi3516EV200 can not be used, after copying in, 
the runtime reports the error that the symbol cannot be found (GK_API_XXXXX)

**Comment by Yury-MonZon** [comment]
Can't comment on that. I've just placed it in the camera and it works. I'm using a GK7205V200 with an imx307 camera.
